# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT BOOT_FLASH CACHE STRING "Type of multi-context")
#-----------------------Build Boot Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Boot.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " Boot)
    ExternalProject_Add(art_pi2_exp_Boot
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/Boot/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/Boot
        PREFIX                      Boot
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/Boot/build")
	set(ST_BOOT_FLASH_BOOT_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/Boot/build/art_pi2_exp_Boot${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to boot project target")
endif()
#-----------------------Build Appli Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Appli.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " Appli)
    ExternalProject_Add(art_pi2_exp_Appli
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/Appli/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/Appli
        PREFIX                      Appli
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/Appli/build")
	set(ST_BOOT_FLASH_APPLI_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/Appli/build/art_pi2_exp_Appli${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to appli project target")
endif()

